package com.Hospital.Management.System.doclogin.controller;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.management.AttributeNotFoundException;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.Hospital.Management.System.doclogin.entity.Medicine;
import com.Hospital.Management.System.doclogin.repository.MedicineRepository;
import com.Hospital.Management.System.entity.Patient;

@CrossOrigin(origins="http://localhost:4200")
@RestController
@RequestMapping("/api/v3/medicine")
public class MedicineController {
	@Autowired
	private MedicineRepository medicineRepository;
	
	@PostMapping()
	public Medicine createMedicine(@RequestBody Medicine medicine) {
		return medicineRepository.save(medicine);
	}
	
	@GetMapping()
	public List<Medicine> getAllMedicine(){
		return medicineRepository.findAll();
	}
	
	@GetMapping("{id}")
	public ResponseEntity<Medicine> getMedicineById(@PathVariable long id) throws AttributeNotFoundException{
		Medicine m = medicineRepository.findById(id).orElseThrow(()->new AttributeNotFoundException("Medicine with Id "+id+" not found"));
		return ResponseEntity.ok(m);
	}
	
	@PutMapping("{id}")
	public ResponseEntity<Medicine> updateMedicine(@PathVariable long id, @RequestBody Medicine m1) throws AttributeNotFoundException{
		Medicine m2 = medicineRepository.findById(id).orElseThrow(()->new AttributeNotFoundException("Medicine with Id "+id+" not found"));
		m2.setDrugName(m1.getDrugName());
		m2.setStock(m1.getStock());
		medicineRepository.save(m2);
		return ResponseEntity.ok(m2);
	}
	@DeleteMapping("{id}")
	public ResponseEntity<Map<String,Boolean>> deleteMedicine(@PathVariable long id) throws AttributeNotFoundException{
		Medicine m = medicineRepository.findById(id).orElseThrow(() -> new AttributeNotFoundException("Medicine with Id "+id+" not found"));
		medicineRepository.delete(m);
		Map<String,Boolean> response = new HashMap<String,Boolean>();
		response.put("Deleted",Boolean.TRUE);
		return ResponseEntity.ok(response);
	}
}
/*
 Note: 
 
findById(id) returns an Optional<Medicine> (or Optional<AClass>). This object acts as a container that either holds a Medicine instance or is empty.

The method .orElseThrow(() -> new Exception(...)) acts as a conditional extractor:
If the Optional is present (not empty): It safely unwraps the contained Medicine object and returns that object as the result of the entire expression.
If the Optional is empty: It throws the exception generated by the supplier function (the lambda expression).
 */
